const sampleData = {
  categories: [
    {
      name: "T-shirts",
      slug: "t-shirts",
      icon: "Shirt",
    },
    {
      name: "Shirt for suits",
      slug: "shirt-for-suits",
      icon: "Shirt",
    },
    {
      name: "Sweatshirts",
      slug: "sweatshirts",
      icon: "Shirt",
    },
    {
      name: "Shoes",
      slug: "shoes",
      icon: "Footprints",
    },
    {
      name: "Jackets",
      slug: "jackets",
      icon: "Shirt",
    },
    {
      name: "Electronic",
      slug: "electronic",
      icon: "Smartphone",
    },
    {
      name: "Home",
      slug: "home",
      icon: "Home",
    },
  ],
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      name: "Classic Stretch Shirt",
      slug: "classic-stretch-shirt",
      categorySlug: "shirt-for-suits",
      description: "Classic style with modern comfort",
      images: [
        "/images/sample-products/clothes/shirt-for-suits/p1-1.jpg",
        "/images/sample-products/clothes/shirt-for-suits/p1-2.jpg",
      ],
      price: 59.99,
      brand: "StyleWear",
      rating: 4.2,
      numReviews: 3,
      stock: 5,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L"],
      colors: ["Light Blue"],
    },
    {
      name: "Long Sleeved Premium Shirt",
      slug: "long-sleeved-premium-shirt",
      categorySlug: "shirt-for-suits",
      description: "Timeless style and premium comfort",
      images: ["/images/sample-products/clothes/shirt-for-suits/p2-1.jpg"],
      price: 85.9,
      brand: "EliteWear",
      rating: 0,
      numReviews: 0,
      stock: 10,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Brown"],
    },
    {
      name: "Classic Fit Dress Shirt",
      slug: "classic-fit-dress-shirt",
      categorySlug: "shirt-for-suits",
      description: "A perfect blend of sophistication and comfort",
      images: ["/images/sample-products/clothes/shirt-for-suits/p3-1.jpg"],
      price: 99.95,
      brand: "FormalStyle",
      rating: 3.8,
      numReviews: 2,
      stock: 0,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Yellow"],
    },
    {
      name: "Slim Fit Stretch Shirt",
      slug: "slim-fit-stretch-shirt",
      categorySlug: "shirt-for-suits",
      description: "Streamlined design with flexible stretch fabric",
      images: ["/images/sample-products/clothes/shirt-for-suits/p4-1.jpg"],
      price: 39.95,
      brand: "ModernFit",
      rating: 4.1,
      numReviews: 4,
      stock: 10,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Olive Green"],
    },
    {
      name: "Oxford Premium Shirt",
      slug: "oxford-premium-shirt",
      categorySlug: "shirt-for-suits",
      description: "Iconic design with refined oxford fabric",
      images: ["/images/sample-products/clothes/shirt-for-suits/p5-1.jpg"],
      price: 79.99,
      brand: "PremiumWear",
      rating: 0,
      numReviews: 0,
      stock: 6,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M"],
      colors: ["Navy Blue"],
    },
    {
      name: "Woman Oxford Premium Shirt",
      slug: "woman-oxford-premium-shirt",
      categorySlug: "shirt-for-suits",
      description: "Iconic design with refined oxford fabric",
      images: [
        "/images/sample-products/clothes/shirt-for-suits/product_03.jpg",
        "/images/sample-products/clothes/shirt-for-suits/product_03b.jpg",
      ],
      price: 79.99,
      brand: "PremiumWear",
      rating: 4.5,
      numReviews: 5,
      stock: 6,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M"],
      colors: ["Navy Blue"],
    },
    {
      name: "Comfort Sweatshirt",
      slug: "comfort-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Cozy and warm sweatshirt perfect for casual everyday wear",
      images: ["/images/sample-products/clothes/sweatshirt/p6-1.jpg"],
      price: 49.99,
      brand: "ComfortWear",
      rating: 4.3,
      numReviews: 6,
      stock: 25,
      isFeatured: true,
      banner: "/images/banner-sweatshirts1.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Pink"],
    },
    {
      name: "Green Classic Sweatshirt",
      slug: "green-classic-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Comfortable green sweatshirt with classic design",
      images: [
        "/images/sample-products/clothes/sweatshirt/2g.png",
        "/images/sample-products/clothes/sweatshirt/2gr.png",
      ],
      price: 54.99,
      brand: "ComfortWear",
      rating: 3.9,
      numReviews: 4,
      stock: 20,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Green", "Brown"],
    },
    {
      name: "Multi-Color Sweatshirt",
      slug: "multi-color-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Versatile sweatshirt available in multiple color options",
      images: [
        "/images/sample-products/clothes/sweatshirt/3b.png",
        "/images/sample-products/clothes/sweatshirt/3bl.png",
        "/images/sample-products/clothes/sweatshirt/3gr.png",
      ],
      price: 59.99,
      brand: "StyleWear",
      rating: 0,
      numReviews: 0,
      stock: 18,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Blue", "Black", "Green"],
    },
    {
      name: "Colorful Sweatshirt Collection",
      slug: "colorful-sweatshirt-collection",
      categorySlug: "sweatshirts",
      description: "Vibrant sweatshirt collection with multiple color choices",
      images: [
        "/images/sample-products/clothes/sweatshirt/5bl.png",
        "/images/sample-products/clothes/sweatshirt/5o.png",
        "/images/sample-products/clothes/sweatshirt/5r.png",
      ],
      price: 64.99,
      brand: "VibrantWear",
      rating: 4.6,
      numReviews: 4,
      stock: 22,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Blue", "Orange", "Red"],
    },
    {
      name: "Casual Apparel Sweatshirt",
      slug: "casual-apparel-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Comfortable casual sweatshirt for everyday wear",
      images: ["/images/sample-products/clothes/sweatshirt/apparel2.jpg"],
      price: 49.99,
      brand: "CasualWear",
      rating: 2.5,
      numReviews: 2,
      stock: 25,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["White"],
    },
    {
      name: "Premium Apparel Sweatshirt",
      slug: "premium-apparel-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Premium quality sweatshirt with soft fabric and modern fit",
      images: [
        "/images/sample-products/clothes/sweatshirt/apparel4.jpg",
        "/images/sample-products/clothes/sweatshirt/apparel5.jpg",
        "/images/sample-products/clothes/sweatshirt/apparel6.jpg",
      ],
      price: 69.99,
      brand: "PremiumWear",
      rating: 4.0,
      numReviews: 1,
      stock: 15,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Navy"],
    },

    {
      name: "Designer Sweatshirt",
      slug: "designer-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Elegant designer sweatshirt with sophisticated style",
      images: [
        "/images/sample-products/clothes/sweatshirt/product_02.jpg",
        "/images/sample-products/clothes/sweatshirt/product_02b.jpg",
      ],
      price: 74.99,
      brand: "DesignWear",
      rating: 5.0,
      numReviews: 6,
      stock: 16,
      isFeatured: true,
      banner: "/images/banner-sweatshirts3.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Black"],
    },
    {
      name: "Premium Sweatshirt",
      slug: "premium-sweatshirt",
      categorySlug: "sweatshirts",
      description: "High-quality premium sweatshirt with excellent comfort",
      images: [
        "/images/sample-products/clothes/sweatshirt/product_04.jpg",
        "/images/sample-products/clothes/sweatshirt/product_04b.jpg",
      ],
      price: 79.99,
      brand: "PremiumStyle",
      rating: 4.7,
      numReviews: 5,
      stock: 14,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Gray"],
    },
    {
      name: "Classic Sweatshirt",
      slug: "classic-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Timeless classic sweatshirt with comfortable fit",
      images: [
        "/images/sample-products/clothes/sweatshirt/product_05.jpg",
        "/images/sample-products/clothes/sweatshirt/product_05b.jpg",
      ],
      price: 64.99,
      brand: "ClassicWear",
      rating: 4.6,
      numReviews: 5,
      stock: 19,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Light Blue"],
    },
    {
      name: "Sport Sweatshirt",
      slug: "sport-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Athletic-style sweatshirt perfect for active lifestyle",
      images: [
        "/images/sample-products/clothes/sweatshirt/product_06.jpg",
        "/images/sample-products/clothes/sweatshirt/product_06b.jpg",
      ],
      price: 69.99,
      brand: "SportWear",
      rating: 0,
      numReviews: 0,
      stock: 17,
      isFeatured: true,
      banner: "/images/banner-sweatshirts2.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Brown"],
    },
    {
      name: "Fashion Sweatshirt",
      slug: "fashion-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Trendy fashion sweatshirt with modern appeal",
      images: [
        "/images/sample-products/clothes/sweatshirt/product_07.jpg",
        "/images/sample-products/clothes/sweatshirt/product_07b.jpg",
      ],
      price: 74.99,
      brand: "FashionStyle",
      rating: 4.4,
      numReviews: 4,
      stock: 21,
      isFeatured: true,
      banner: "/images/banner-sweatshirts3.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Pink", "White"],
    },
    {
      name: "Urban Sweatshirt",
      slug: "urban-sweatshirt",
      categorySlug: "sweatshirts",
      description: "Urban style sweatshirt with street appeal",
      images: [
        "/images/sample-products/clothes/sweatshirt/product_08.jpg",
        "/images/sample-products/clothes/sweatshirt/product_08b.jpg",
      ],
      price: 64.99,
      brand: "UrbanWear",
      rating: 4.5,
      numReviews: 4,
      stock: 20,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red"],
    },
    {
      name: "Classic Leather Sneakers",
      slug: "classic-leather-sneakers",
      categorySlug: "shoes",
      description:
        "Premium leather sneakers with comfortable fit and timeless design",
      images: [
        "/images/sample-products/shoes/6a.png",
        "/images/sample-products/shoes/6b.png",
      ],
      price: 129.99,
      brand: "FootStyle",
      rating: 4.9,
      numReviews: 6,
      stock: 20,
      isFeatured: true,
      banner: "/images/banner-shoes2.jpg",
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46"],
      colors: ["Black", "White"],
    },
    {
      name: "Sport Running Shoes",
      slug: "sport-running-shoes",
      categorySlug: "shoes",
      description:
        "High-performance running shoes with advanced cushioning technology",
      images: [
        "/images/sample-products/shoes/7a.png",
        "/images/sample-products/shoes/7b.png",
      ],
      price: 149.99,
      brand: "RunFast",
      rating: 4.8,
      numReviews: 4,
      stock: 18,
      isFeatured: true,
      banner: "/images/banner-shoes.png",
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46", "47"],
      colors: ["Gray", "Pink"],
    },
    {
      name: "Casual Canvas Shoes",
      slug: "casual-canvas-shoes",
      categorySlug: "shoes",
      description: "Comfortable canvas shoes perfect for everyday casual wear",
      images: ["/images/sample-products/shoes/shoe2.jpg"],
      price: 49.99,
      brand: "ComfortStep",
      rating: 0,
      numReviews: 0,
      stock: 30,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45"],
      colors: ["Beige"],
    },
    {
      name: "Elegant Dress Shoes",
      slug: "elegant-dress-shoes",
      categorySlug: "shoes",
      description:
        "Sophisticated dress shoes for formal occasions and business wear",
      images: ["/images/sample-products/shoes/shoe3.jpg"],
      price: 179.99,
      brand: "FormalStep",
      rating: 4.6,
      numReviews: 3,
      stock: 15,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46"],
      colors: ["Black", "Brown"],
    },
    {
      name: "Urban Street",
      slug: "urban-street",
      categorySlug: "shoes",
      description: "Stylish urban with modern design and street appeal",
      images: ["/images/sample-products/shoes/shoe4.jpg"],
      price: 89.99,
      brand: "UrbanWalk",
      rating: 3.5,
      numReviews: 1,
      stock: 22,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45"],
      colors: ["Green"],
    },
    {
      name: "Classic Oxford Shoes",
      slug: "classic-oxford-shoes",
      categorySlug: "shoes",
      description:
        "Timeless oxford shoes with premium leather and classic styling",
      images: ["/images/sample-products/shoes/shoe5.jpg"],
      price: 199.99,
      brand: "PremiumStep",
      rating: 4.9,
      numReviews: 6,
      stock: 12,
      isFeatured: true,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46"],
      colors: ["Black"],
    },
    {
      name: "Comfort Walking Shoes",
      slug: "comfort-walking-shoes",
      categorySlug: "shoes",
      description:
        "Lightweight walking shoes with excellent support for long walks",
      images: ["/images/sample-products/shoes/shoe6.jpg"],
      price: 79.99,
      brand: "WalkEasy",
      rating: 0,
      numReviews: 0,
      stock: 25,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46"],
      colors: ["Light Green"],
    },
    {
      name: "Athletic Training Shoes",
      slug: "athletic-training-shoes",
      categorySlug: "shoes",
      description:
        "Versatile training shoes for gym workouts and athletic activities",
      images: ["/images/sample-products/shoes/shoe7.jpg"],
      price: 119.99,
      brand: "FitStep",
      rating: 4.2,
      numReviews: 6,
      stock: 19,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46", "47"],
      colors: ["White"],
    },
    {
      name: "Minimalist Sneakers",
      slug: "minimalist-sneakers",
      categorySlug: "shoes",
      description: "Clean and simple design sneakers with minimalist aesthetic",
      images: ["/images/sample-products/shoes/shoe8.jpg"],
      price: 69.99,
      brand: "SimpleStep",
      rating: 4.5,
      numReviews: 2,
      stock: 28,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45"],
      colors: ["Brown"],
    },
    {
      name: "Premium Boots",
      slug: "premium-boots",
      categorySlug: "shoes",
      description:
        "Durable and stylish boots for all seasons with premium materials",
      images: ["/images/sample-products/shoes/shoe9.jpg"],
      price: 159.99,
      brand: "BootMaster",
      rating: 0,
      numReviews: 0,
      stock: 16,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["41", "42", "43", "44", "45", "46"],
      colors: ["Red"],
    },
    {
      name: "Apex Pro Max",
      slug: "apex-pro-max",
      categorySlug: "electronic",
      description:
        "Latest flagship smartphone with titanium design and advanced chip",
      images: ["/images/sample-products/electronic/1.png"],
      price: 1199.99,
      brand: "Apex",
      rating: 4.9,
      numReviews: 5,
      stock: 25,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Stellar Ultra",
      slug: "stellar-ultra",
      categorySlug: "electronic",
      description:
        "Premium Android device with stylus and advanced AI features",
      images: ["/images/sample-products/electronic/2.png"],
      price: 1099.99,
      brand: "Stellar",
      rating: 3.4,
      numReviews: 3,
      stock: 18,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Nexus 8 Pro",
      slug: "nexus-8-pro",
      categorySlug: "electronic",
      description:
        "Pure Android experience with exceptional camera and AI capabilities",
      images: ["/images/sample-products/electronic/3.png"],
      price: 899.99,
      brand: "Nexus",
      rating: 4.7,
      numReviews: 2,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Prime 12",
      slug: "prime-12",
      categorySlug: "electronic",
      description: "Flagship killer with latest processor and fast charging",
      images: ["/images/sample-products/electronic/4.png"],
      price: 799.99,
      brand: "Prime",
      rating: 0,
      numReviews: 0,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Xeno 14 Pro",
      slug: "xeno-14-pro",
      categorySlug: "electronic",
      description:
        "High-performance device with premium camera system and premium build",
      images: ["/images/sample-products/electronic/5.png"],
      price: 749.99,
      brand: "Xeno",
      rating: 4.5,
      numReviews: 4,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Horizon P60 Pro",
      slug: "horizon-p60-pro",
      categorySlug: "electronic",
      description:
        "Premium photography smartphone with advanced camera technology",
      images: ["/images/sample-products/electronic/6.png"],
      price: 999.99,
      brand: "Horizon",
      rating: 2.1,
      numReviews: 1,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Spectra 1 V",
      slug: "spectra-1-v",
      categorySlug: "electronic",
      description:
        "Professional-grade camera phone with 4K display and audio features",
      images: ["/images/sample-products/electronic/8.png"],
      price: 1299.99,
      brand: "Spectra",
      rating: 4.5,
      numReviews: 2,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "MotoTech Edge 40 Pro",
      slug: "mototech-edge-40-pro",
      categorySlug: "electronic",
      description:
        "Sleek design with powerful performance and clean Android experience",
      images: ["/images/sample-products/electronic/10.png"],
      price: 649.99,
      brand: "MotoTech",
      rating: 3.6,
      numReviews: 3,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Null Phone 2",
      slug: "null-phone-2",
      categorySlug: "electronic",
      description:
        "Unique transparent design with LED interface and smooth performance",
      images: ["/images/sample-products/electronic/11.png"],
      price: 599.99,
      brand: "Null",
      rating: 4.4,
      numReviews: 5,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Optima Find X6 Pro",
      slug: "optima-find-x6-pro",
      categorySlug: "electronic",
      description:
        "Premium flagship with professional camera and fast charging",
      images: ["/images/sample-products/electronic/12.png"],
      price: 949.99,
      brand: "Optima",
      rating: 0,
      numReviews: 0,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Vortex X100 Pro",
      slug: "vortex-x100-pro",
      categorySlug: "electronic",
      description:
        "Photography-focused smartphone with premium optics and powerful chip",
      images: ["/images/sample-products/electronic/13.png"],
      price: 899.99,
      brand: "Vortex",
      rating: 4.9,
      numReviews: 4,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Realm GT 5 Pro",
      slug: "realm-gt-5-pro",
      categorySlug: "electronic",
      description:
        "Gaming-focused device with latest processor and high refresh rate",
      images: ["/images/sample-products/electronic/14.png"],
      price: 699.99,
      brand: "Realm",
      rating: 3.8,
      numReviews: 2,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Halo Magic 6 Pro",
      slug: "halo-magic-6-pro",
      categorySlug: "electronic",
      description: "Flagship device with advanced AI and premium camera system",
      images: ["/images/sample-products/electronic/15.png"],
      price: 849.99,
      brand: "Halo",
      rating: 4.1,
      numReviews: 6,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Atlas ROG Phone 8",
      slug: "atlas-rog-phone-8",
      categorySlug: "electronic",
      description:
        "Ultimate gaming smartphone with advanced cooling and high performance",
      images: ["/images/sample-products/electronic/16.jpg"],
      price: 1099.99,
      brand: "Atlas",
      rating: 4.2,
      numReviews: 3,
      stock: 7,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Premium USB-C Cable",
      slug: "premium-usb-c-cable",
      categorySlug: "electronic",
      description:
        "High-speed USB-C cable with fast charging and data transfer support",
      images: ["/images/sample-products/electronic/usb-cable.jpg"],
      price: 19.99,
      brand: "CablePro",
      rating: 4.6,
      numReviews: 4,
      stock: 150,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Gaming Laptop Pro",
      slug: "gaming-laptop-pro",
      categorySlug: "electronic",
      description:
        "High-performance gaming laptop with RTX graphics and fast processor",
      images: ["/images/sample-products/electronic/laptop.jpg"],
      price: 1799.99,
      brand: "PowerBook",
      rating: 4.7,
      numReviews: 5,
      stock: 15,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Wireless Noise Cancelling Headphones",
      slug: "wireless-noise-cancelling-headphones",
      categorySlug: "electronic",
      description:
        "Premium over-ear headphones with active noise cancellation and long battery life",
      images: ["/images/sample-products/electronic/headphones.jpg"],
      price: 349.99,
      brand: "SoundWave",
      rating: 5.0,
      numReviews: 6,
      stock: 45,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Ultra-Wide Curved Monitor",
      slug: "ultra-wide-curved-monitor",
      categorySlug: "electronic",
      description:
        "34-inch curved gaming monitor with 4K resolution and high refresh rate",
      images: ["/images/sample-products/electronic/big-monitor.jpg"],
      price: 599.99,
      brand: "VisionPro",
      rating: 3.3,
      numReviews: 1,
      stock: 28,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Comfortable Bed Frame",
      slug: "comfortable-bed-frame",
      categorySlug: "home",
      description:
        "Modern bed frame with elegant design and sturdy construction",
      images: ["/images/sample-products/home/bed.jpg"],
      price: 599.99,
      brand: "HomeComfort",
      rating: 4.4,
      numReviews: 3,
      stock: 15,
      isFeatured: true,
      banner: "/images/banner-home.jpg",
    },
    {
      name: "Elegant Ceiling Lamp",
      slug: "elegant-ceiling-lamp",
      categorySlug: "home",
      description: "Stylish ceiling lamp with modern design and warm lighting",
      images: ["/images/sample-products/home/ceiling-lamp.jpg"],
      price: 149.99,
      brand: "LightStyle",
      rating: 0,
      numReviews: 0,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Designer Chair",
      slug: "designer-chair",
      categorySlug: "home",
      description:
        "Comfortable designer chair with ergonomic support and premium materials",
      images: ["/images/sample-products/home/chair.jpg"],
      price: 249.99,
      brand: "FurniturePro",
      rating: 4.6,
      numReviews: 4,
      stock: 22,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Classic Chest of Drawers",
      slug: "classic-chest-of-drawers",
      categorySlug: "home",
      description:
        "Spacious chest of drawers with multiple compartments and elegant finish",
      images: ["/images/sample-products/home/chest-of-drawers.jpg"],
      price: 399.99,
      brand: "StorageMax",
      rating: 2.4,
      numReviews: 1,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Soft Decorative Pillows",
      slug: "soft-decorative-pillows",
      categorySlug: "home",
      description:
        "Set of comfortable decorative pillows to enhance your living space",
      images: ["/images/sample-products/home/pillows.jpg"],
      price: 39.99,
      brand: "HomeDecor",
      rating: 3.1,
      numReviews: 2,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Classic Green T-Shirt",
      slug: "classic-green-t-shirt",
      categorySlug: "t-shirts",
      description: "Comfortable classic t-shirt in green with modern fit",
      images: [
        "/images/sample-products/clothes/t-shirts/1g.png",
        "/images/sample-products/clothes/t-shirts/1gr.png",
      ],
      price: 29.99,
      brand: "StyleWear",
      rating: 4.3,
      numReviews: 5,
      stock: 25,
      isFeatured: true,
      banner: "/images/banner-tshirts.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Green"],
    },
    {
      name: "Premium Pink T-Shirt",
      slug: "premium-pink-t-shirt",
      categorySlug: "t-shirts",
      description: "Soft premium t-shirt in pink color with comfortable fabric",
      images: ["/images/sample-products/clothes/t-shirts/1p.png"],
      price: 34.99,
      brand: "ComfortWear",
      rating: 0,
      numReviews: 0,
      stock: 20,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Purple"],
    },
    {
      name: "Casual Pink White T-Shirt",
      slug: "casual-pink-white-t-shirt",
      categorySlug: "t-shirts",
      description: "Versatile t-shirt available in pink and white colors",
      images: [
        "/images/sample-products/clothes/t-shirts/4p.png",
        "/images/sample-products/clothes/t-shirts/4w.png",
      ],
      price: 27.99,
      brand: "CasualStyle",
      rating: 4.8,
      numReviews: 3,
      stock: 30,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Orange", "Beige"],
    },
    {
      name: "Modern Classic T-Shirt",
      slug: "modern-classic-t-shirt",
      categorySlug: "t-shirts",
      description: "Modern classic t-shirt with contemporary design and fit",
      images: [
        "/images/sample-products/clothes/t-shirts/product_01.jpg",
        "/images/sample-products/clothes/t-shirts/product_01b.jpg",
      ],
      price: 32.99,
      brand: "ModernFit",
      rating: 3.7,
      numReviews: 2,
      stock: 22,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Light Green"],
    },
    {
      name: "Blue Gray Jacket",
      slug: "blue-gray-jacket",
      categorySlug: "jackets",
      description: "Stylish jacket available in blue and gray color options",
      images: [
        "/images/sample-products/clothes/jackets/8b.png",
        "/images/sample-products/clothes/jackets/8gr.png",
      ],
      price: 89.99,
      brand: "OuterWear",
      rating: 4.3,
      numReviews: 5,
      stock: 18,
      isFeatured: true,
      banner: "/images/banner-jacket1.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Blue", "Green"],
    },
    {
      name: "Casual Apparel Jacket",
      slug: "casual-apparel-jacket",
      categorySlug: "jackets",
      description: "Comfortable casual jacket perfect for everyday wear",
      images: ["/images/sample-products/clothes/jackets/apparel1.jpg"],
      price: 79.99,
      brand: "CasualWear",
      rating: 0,
      numReviews: 0,
      stock: 15,
      isFeatured: true,
      banner: "/images/banner-jacket2.jpg",
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"],
    },
    {
      name: "Premium Apparel Jacket",
      slug: "premium-apparel-jacket",
      categorySlug: "jackets",
      description: "Premium quality jacket with modern design and comfort",
      images: ["/images/sample-products/clothes/jackets/apparel3.jpg"],
      price: 99.99,
      brand: "PremiumOuter",
      rating: 4.0,
      numReviews: 4,
      stock: 12,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"],
    },
    {
      name: "Designer Jacket",
      slug: "designer-jacket",
      categorySlug: "jackets",
      description: "Elegant designer jacket with sophisticated style",
      images: [
        "/images/sample-products/clothes/jackets/ig_03.jpg",
        "/images/sample-products/clothes/jackets/ig_05.jpg",
      ],
      price: 119.99,
      brand: "DesignWear",
      rating: 2.9,
      numReviews: 1,
      stock: 10,
      isFeatured: false,
      banner: null,
      hasVariants: true,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Brown"],
    },
  ],
};

export default sampleData;
