const CONTENT_PAGE = {
  HEADER: {
    cart: "Cart",
    signIn: "Sign In",
  },
  FOOTER: {
    allRightsReserved: "All Rights Reserved",
  },
  MODE_TOGGLE: {
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  MENU: {
    menu: "Menu",
  },
  USER_BUTTON: {
    userProfile: "User Profile",
    orderHistory: "Order History",
    admin: "Admin",
    signOut: "Sign Out",
  },
  PRODUCT_LIST: {
    noProductsFound: "No products found",
  },
  PRODUCT_CARD: {
    outOfStock: "Out of Stock",
    inStock: "In Stock",
  },
  PRODUCT_DETAILS: {
    description: "Description",
    price: "Price",
    status: "Status",
    addToCart: "Add to Cart",
    reviews: "Reviews",
  },
  SIGN_IN_PAGE: {
    signIn: "Sign In",
    signInToYourAccount: "Sign in to your account",
  },
  SIGN_IN_PAGE_CREDENTIALS_FORM: {
    email: "Email",
    password: "Password",
    signUp: "Sign Up",
    text: "Don't have an account?",
  },
  BUTTON_CREDENTIALS_SIGN_IN: {
    signIn: "Sign In",
    signing: "Signing in...",
  },
  SIGN_UP_PAGE: {
    createAccount: "Create Account",
    enterYourInformationBelowToSignUp:
      "Enter your information below to sign up",
  },
  SIGN_UP_FORM: {
    name: "Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign In",
  },
  BUTTON_SIGN_UP_FORM: {
    submitting: "Submitting...",
    signUp: "Sign Up",
  },
  CART_PAGE: {
    shoppingCart: "Shopping Cart",
    cartIsEmpty: "Cart is empty.",
    goShopping: "Go Shopping",
    item: "Item",
    quantity: "Quantity",
    price: "Price",
    subTotal: "Subtotal",
    proceedToCheckout: "Proceed to Checkout",
  },
  SHIPPING_ADDRESS_FORM: {
    shippingAddress: "Shipping Address",
    pleaseEnterAddressToShipTo: "Please enter and address to ship to",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    address: "Address",
    enterAddress: "Enter address",
    city: "City",
    enterCity: "Enter city",
    postalCode: "Postal Code",
    enterPostalCode: "Enter postal code",
    country: "Country",
    enterCountry: "Enter country",
    continue: "Continue",
  },
  PAYMENT_METHOD_FORM: {
    paymentMethod: "Payment Method",
    pleaseSelectPaymentMethod: "Please select a payment method",
    continue: "Continue",
  },
  PLACE_ORDER_PAGE: {
    placeOrder: "Place Order",
    shippingAddress: "Shipping Address",
    paymentMethod: "Payment Method",
    orderItems: "Order Items",
    item: "Item",
    quantity: "Quantity",
    price: "Price",
    edit: "Edit",
    items: "Items",
    tax: "Tax",
    shipping: "Shipping",
    total: "Total",
  },
  ORDER_DETAILS_PAGE: {
    order: "Order",
    paymentMethod: "Payment Method",
    paidAt: "Paid at",
    notPaid: "Not paid",
    shippingAddress: "Shipping Address",
    deliveredAt: "Delivered at",
    notDelivered: "Not Delivered",
    orderItems: "Order Items",
    item: "Item",
    quantity: "Quantity",
    price: "Price",
    edit: "Edit",
    items: "Items",
    tax: "Tax",
    shipping: "Shipping",
    total: "Total",
  },
  USER_ORDERS_PAGE: {
    orders: "Orders",
    orderId: "Order ID",
    date: "Date",
    total: "Total",
    paid: "Paid",
    delivered: "Delivered",
    actions: "Actions",
    notPaid: "Not Paid",
    notDelivered: "Not Delivered",
  },
  PAGINATION: {
    previous: "Previous",
    next: "Next",
  },
  USER_PROFILE_PAGE: {
    title: "Profile",
    updateProfile: "Update Profile",
    email: "Email",
    name: "Name",
    update: "Update",
    submitting: "Submitting...",
  },
  ADMIN_OVERVIEW_PAGE: {
    title: "Admin Dashboard",
    totalRevenue: "Total Revenue",
    sales: "Sales",
    customers: "Customers",
    products: "Products",
    recentSales: "Recent Sales",
    overview: "Overview",
    buyer: "Buyer",
    date: "Date",
    total: "Total",
    actions: "Actions",
    details: "Details",
    deletedUser: "Deleted User",
  },
  ADMIN_ORDERS_PAGE: {
    orders: "Orders",
    filteredBy: "Filtered by",
    removeFilter: "Remove Filter",
    orderId: "Order ID",
    date: "Date",
    total: "Total",
    paid: "Paid",
    delivered: "Delivered",
    actions: "Actions",
    details: "Details",
    deletedUser: "Deleted User",
    buyer: "Buyer",
    notPaid: "Not Paid",
    notDelivered: "Not Delivered",
  },
  ADMIN_PRODUCTS_PAGE: {
    products: "Products",
    filteredBy: "Filtered by",
    removeFilter: "Remove Filter",
    createProduct: "Create Product",
    id: "ID",
    name: "Name",
    price: "Price",
    category: "Category",
    stock: "Stock",
    rating: "Rating",
    actions: "Actions",
    editProduct: "Edit",
  },
  ADMIN_PRODUCTS_CREATE_PAGE: {
    createProduct: "Create Product",
  },
  ADMIN_PRODUCTS_FORM: {
    name: "Name",
    slug: "Slug",
    category: "Category",
    brand: "Brand",
    price: "Price",
    stock: "Stock",
    description: "Description",
    images: "Images",
    isFeatured: "Is Featured",
    banner: "Banner",
    create: "Create",
    update: "Update",
    submitting: "Submitting...",
    productCreated: "Product created successfully",
    productUpdated: "Product updated successfully",
    productDeleted: "Product deleted successfully",
    productNotFound: "Product not found",
    generate: "Generate",
    enterProductName: "Enter product name",
    enterSlug: "Enter slug",
    enterCategory: "Enter category",
    enterBrand: "Enter brand",
    enterPrice: "Enter price",
    enterStock: "Enter stock",
    enterDescription: "Enter product description",
    featuredProduct: "Featured Product",
    removeBanner: "Remove Banner",
    product: "Product",
  },
  ADMIN_PRODUCTS_UPDATE_PAGE: {
    updateProduct: "Update Product",
  },
  ADMIN_USERS_PAGE: {
    users: "Users",
    filteredBy: "Filtered by",
    removeFilter: "Remove Filter",
    id: "ID",
    name: "Name",
    email: "Email",
    role: "Role",
    actions: "Actions",
    edit: "Edit",
    user: "User",
    admin: "Admin",
  },
  ADMIN_USERS_UPDATE_PAGE: {
    updateUser: "Update User",
  },
  ADMIN_USERS_UPDATE_FORM: {
    email: "Email",
    emailPlaceholder: "Enter user email",
    name: "Name",
    namePlaceholder: "Enter user name",
    role: "Role",
    rolePlaceholder: "Select a role",
    updateUser: "Update User",
    submitting: "Submitting...",
  },
  DELETE_DIALOG: {
    areYouAbsolutelySure: "Are you absolutely sure?",
    thisActionCannotBeUndone: "This action cannot be undone",
    cancel: "Cancel",
    delete: "Delete",
    deleting: "Deleting...",
  },
  UNAUTHORIZED_PAGE: {
    title: "Unauthorized Access",
    text: "You do not have permission to access this page.",
    returnHome: "Return Home",
  },
  MARK_AS_PAID: {
    markAsPaid: "Mark As Paid",
    processing: "Processing...",
  },
  MARK_AS_DELIVERED: {
    markAsDelivered: "Mark As Delivered",
    processing: "Processing...",
  },
  PAYPAL_LOADING_STATE: {
    loading: "Loading PayPal...",
    error: "Error Loading PayPal",
  },
  ADMIN_SEARCH: {
    search: "Search...",
  },
  CATEGORY_DRAWER: {
    selectCategory: "Select a category",
  },
};

export default CONTENT_PAGE;
