const CONTENT_PAGE = {
  GLOBAL: {
    currencySymbol: "$",
    name: "Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    price: "Price",
    quantity: "Quantity",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    continue: "Continue",
    update: "Update",
    create: "Create",
    submitting: "Submitting...",
    processing: "Processing...",
    deleting: "Deleting...",
    saving: "Saving...",
    status: "Status",
    stock: "Stock",
    rating: "Rating",
    category: "Category",
    brand: "Brand",
    description: "Description",
    images: "Images",
    item: "Item",
    items: "Items",
    total: "Total",
    tax: "Tax",
    shipping: "Shipping",
    subtotal: "Subtotal",
    signIn: "Sign In",
    signOut: "Sign Out",
    signUp: "Sign Up",
    id: "ID",
    date: "Date",
    paid: "Paid",
    delivered: "Delivered",
    notPaid: "Not Paid",
    notDelivered: "Not Delivered",
    details: "Details",
    buyer: "Buyer",
    user: "User",
    admin: "Admin",
    role: "Role",
    slug: "Slug",
    icon: "Icon",
    products: "Products",
    product: "Product",
    remove: "Remove",
    removeFilter: "Remove Filter",
    filteredBy: "Filtered by",
    search: "Search...",
    all: "All",
    any: "Any",
    previous: "Previous",
    next: "Next",
    goShopping: "Go Shopping",
    viewProduct: "View Product",
    viewProducts: "View Products",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    noProductsFound: "No products found",
    areYouAbsolutelySure: "Are you absolutely sure?",
    thisActionCannotBeUndone: "This action cannot be undone",
    noCategoriesFound: "No categories found",
    // Common messages
    close: "Close",
    goToCart: "Go To Cart",
    notAvailable: "N/A",
    inStockLabel: "in stock",
    // Toast messages
    removedFromWishlist: "removed from wishlist",
    removedFromComparison: "removed from comparison",
    addedToCart: "added to cart",
    updatedInCart: "updated in cart",
    // Form validation messages
    pleaseFixFormErrors: "Please fix the form errors before submitting",
    // Validation error messages
    nameMinLength: "Name must be at least 3 characters",
    slugMinLength: "Slug must be at least 3 characters",
    categoryRequired: "Category is required",
    brandMinLength: "Brand must be at least 3 characters",
    descriptionMinLength: "Description must be at least 3 characters",
    productImageRequired: "Product must have at least one image",
    idRequired: "Id is required",
    invalidEmail: "Invalid email address",
    passwordMinLength: "Password must be at least 6 characters",
    confirmPasswordMinLength: "Confirm password must be at least 6 characters",
    passwordsDontMatch: "Passwords don't match",
    productRequired: "Product is required",
    nameRequired: "Name is required",
    slugRequired: "Slug is required",
    quantityPositive: "Quantity must be a positive number",
    imageRequired: "Image is required",
    sessionCartIdRequired: "Session cart id is required",
    addressMinLength: "Address must be at least 3 characters",
    cityMinLength: "City must be at least 3 characters",
    postalCodeMinLength: "Postal code must be at least 3 characters",
    countryMinLength: "Country must be at least 3 characters",
    paymentMethodRequired: "Payment method is required",
    invalidPaymentMethod: "Invalid payment method",
    userRequired: "User is required",
    priceDecimalPlaces: "Price must have exactly two decimal places",
    emailMinLength: "Email must be at least 3 characters",
    roleRequired: "Role is required",
    titleMinLength: "Title must be at least 3 characters",
    ratingMin: "Rating must be at least 1",
    ratingMax: "Rating must be at most 5",
    promotionEndDateRequired: "Promotion end date is required",
    // Error messages
    errorOccurred: "An error occurred",
    notEnoughStock: "We don't have enough stock of",
    availableStock: "Available stock",
    failedToSetPromotion: "Failed to set promotion",
    promotionClearedSuccessfully: "Promotion cleared successfully",
    promotionSetSuccessfully: "Promotion set successfully",
    managePromotion: "Manage Promotion",
    failedToClearPromotion: "Failed to clear promotion",
    // Product variants
    size: "Size:",
    selectSize: "Select size",
    color: "Color:",
    selectColor: "Select color",
    selectProduct: "Select a product",
    separator: " • ",
    quickAdd: "Quick Add",
    clearing: "Clearing...",
    disabledNotShownOnSite: "Disabled (not shown on site)",
    enabled: "Enabled",
    currentPromotion: "Current Promotion",
    endDate: "End Date",
    loading: "Loading...",
    clear: "Clear",
  },
  PAGE: {
    SIGN_IN: {
      signInToYourAccount: "Sign in to your account",
    },
    SIGN_UP: {
      createAccount: "Create Account",
      enterYourInformationBelowToSignUp:
        "Enter your information below to sign up",
    },
    HOME: {
      newestArrivals: "Newest Arrivals",
      allProducts: "All Products",
    },
    CART: {
      shoppingCart: "Shopping Cart",
      cartIsEmpty: "Cart is empty.",
      proceedToCheckout: "Proceed to Checkout",
      clearAllCart: "Clear All Cart",
    },
    SHIPPING_ADDRESS: {
      shippingAddress: "Shipping Address",
      pleaseEnterAddressToShipTo: "Please enter and address to ship to",
      fullName: "Full Name",
      address: "Address",
      city: "City",
      postalCode: "Postal Code",
      country: "Country",
    },
    PAYMENT_METHOD: {
      paymentMethod: "Payment Method",
    },
    PLACE_ORDER: {
      placeOrder: "Place Order",
      shippingAddress: "Shipping Address",
      paymentMethod: "Payment Method",
      orderItems: "Order Items",
    },
    ORDER_DETAILS: {
      order: "Order",
      paymentMethod: "Payment Method",
      paidAt: "Paid at",
      notPaid: "Not paid",
      shippingAddress: "Shipping Address",
      deliveredAt: "Delivered at",
      notDelivered: "Not Delivered",
      orderItems: "Order Items",
    },
    USER_ORDERS: {
      orders: "Orders",
      orderId: "Order ID",
    },
    USER_PROFILE: {
      title: "Profile",
      updateProfile: "Update Profile",
    },
    ADMIN_OVERVIEW: {
      title: "Admin Dashboard",
      totalRevenue: "Total Revenue",
      sales: "Sales",
      customers: "Customers",
      products: "Products",
      recentSales: "Recent Sales",
      overview: "Overview",
      deletedUser: "Deleted User",
    },
    ADMIN_ORDERS: {
      orders: "Orders",
      orderId: "Order ID",
    },
    ADMIN_PRODUCTS: {
      products: "Products",
      createProduct: "Create Product",
    },
    ADMIN_PRODUCTS_CREATE: {
      createProduct: "Create Product",
    },
    ADMIN_PRODUCTS_UPDATE: {
      updateProduct: "Update Product",
    },
    ADMIN_USERS: {
      users: "Users",
    },
    ADMIN_USERS_UPDATE: {
      updateUser: "Update User",
    },
    ADMIN_CATEGORIES: {
      categories: "Categories",
      createCategory: "Create Category",
      updateCategory: "Update Category",
    },
    ADMIN_PROMOTION: {
      promotion: "Promotion",
      createPromotion: "Create Promotion",
      updatePromotion: "Update Promotion",
    },
    SEARCH: {
      department: "Department",
      customerRatings: "Customer Ratings",
      sortBy: "Sort by",
      newest: "Newest",
      lowest: "Lowest",
      highest: "Highest",
      rating: "Rating",
      query: "Query:",
      category: "Category:",
      price: "Price:",
      ratingLabel: "Rating:",
      starsAndUp: "stars & up",
    },
    UNAUTHORIZED: {
      title: "Unauthorized Access",
      text: "You do not have permission to access this page.",
      returnHome: "Return Home",
    },
    STRIPE_PAYMENT_SUCCESS: {
      thanksForYourPurchase: "Thanks for your purchase",
      weAreProcessingYourOrder: "We are processing your order.",
      viewOrder: "View Order",
    },
    NOT_FOUND: {
      pageNotFound: "Page Not Found",
      couldNotFindRequestedPage: "Could not find requested page",
      backToHome: "Back To Home",
    },
  },
  COMPONENT: {
    HEADER: {
      cart: "Cart",
      wishlist: "Wishlist",
      comparison: "Comparison",
    },
    FOOTER: {
      allRightsReserved: "All Rights Reserved",
    },
    MODE_TOGGLE: {
      appearance: "Appearance",
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    MENU: {
      menu: "Menu",
    },
    USER_BUTTON: {
      userProfile: "User Profile",
      orderHistory: "Order History",
      admin: "Admin",
      signOut: "Sign Out",
    },
    PRODUCT_LIST: {},
    PRODUCT_CARD: {},
    PRODUCT_DETAILS: {
      addToCart: "Add to Cart",
      reviews: "Reviews",
      customerReviews: "Customer Reviews",
      addToWishlist: "Add to Wishlist",
      removeFromWishlist: "Remove from Wishlist",
      addToComparison: "Add to Comparison",
      removeFromComparison: "Remove from Comparison",
    },
    SIGN_IN_FORM: {
      text: "Don't have an account?",
    },
    BUTTON_SIGN_IN: {
      signing: "Signing in...",
    },
    SIGN_UP_FORM: {
      alreadyHaveAccount: "Already have an account?",
    },
    BUTTON_SIGN_UP: {
      submitting: "Submitting...",
      signUp: "Sign Up",
    },
    CART_TABLE: {},
    SHIPPING_ADDRESS_FORM: {
      shippingAddress: "Shipping Address",
      pleaseEnterAddressToShipTo: "Please enter and address to ship to",
      fullName: "Full Name",
      address: "Address",
      city: "City",
      postalCode: "Postal Code",
      country: "Country",
      enterFullName: "Enter full name",
      enterAddress: "Enter address",
      enterCity: "Enter city",
      enterPostalCode: "Enter postal code",
      enterCountry: "Enter country",
    },
    PAYMENT_METHOD_FORM: {
      paymentMethod: "Payment Method",
      pleaseSelectPaymentMethod: "Please select a payment method",
    },
    PLACE_ORDER_FORM: {},
    ORDER_DETAILS_TABLE: {},
    PAGINATION: {},
    ADMIN_PRODUCTS_FORM: {
      name: "Name",
      slug: "Slug",
      category: "Category",
      brand: "Brand",
      price: "Price",
      stock: "Stock",
      description: "Description",
      images: "Images",
      isFeatured: "Is Featured",
      banner: "Banner",
      create: "Create",
      update: "Update",
      submitting: "Submitting...",
      productCreated: "Product created successfully",
      productUpdated: "Product updated successfully",
      productDeleted: "Product deleted successfully",
      productNotFound: "Product not found",
      generate: "Generate",
      enterProductName: "Enter product name",
      enterSlug: "Enter slug",
      enterCategory: "Enter category",
      enterBrand: "Enter brand",
      enterPrice: "Enter price",
      enterStock: "Enter stock",
      enterDescription: "Enter product description",
      featuredProduct: "Featured Product",
      removeBanner: "Remove Banner",
      product: "Product",
    },
    ADMIN_USERS_UPDATE_FORM: {
      email: "Email",
      emailPlaceholder: "Enter user email",
      name: "Name",
      namePlaceholder: "Enter user name",
      role: "Role",
      rolePlaceholder: "Select a role",
      updateUser: "Update User",
      submitting: "Submitting...",
    },
    DELETE_DIALOG: {},
    MARK_AS_PAID: {
      markAsPaid: "Mark As Paid",
      processing: "Processing...",
    },
    MARK_AS_DELIVERED: {
      markAsDelivered: "Mark As Delivered",
      processing: "Processing...",
    },
    PAYPAL_LOADING_STATE: {
      loading: "Loading PayPal...",
      error: "Error Loading PayPal",
    },
    ADMIN_SEARCH: {},
    SEARCH: {},
    CATEGORY_DRAWER: {
      selectCategory: "Select a category",
    },
    BUTTON: {
      viewAllProductsButton: "View All Products",
    },
    REVIEW_LIST: {
      noReviewsYet: "No reviews yet",
      please: "Please",
      signIn: "Sign In",
      toWriteReview: "to write a review",
    },
    REVIEW_FORM: {
      writeReview: "Write a Review",
      shareYourThoughts: "Share your thoughts with other customers",
      title: "Title",
      description: "Description",
      rating: "Rating",
      submitReview: "Submit Review",
      submitting: "Submitting...",
      enterTitle: "Enter title",
      enterDescription: "Enter description",
    },
    STRIPE_PAYMENT: {
      stripeCheckout: "Stripe Checkout",
      purchasing: "Purchasing...",
      purchase: "Purchase",
    },
    ICON_BOXES: {
      freeShipping: "Free Shipping",
      freeShippingDescription: "Free shipping on orders above $100",
      moneyBackGuarantee: "Money Back Guarantee",
      moneyBackGuaranteeDescription: "Within 30 days of purchase",
      flexiblePayment: "Flexible Payment",
      flexiblePaymentDescription: "Pay with credit card, PayPal or COD",
      support: "24/7 Support",
      supportDescription: "Get support at any time",
    },
    PROMOTION_COUNTDOWN: {
      dealOfTheMonth: "Deal Of The Month",
      dealOfTheMonthDescription:
        "Get ready for a shopping experience like never before with our Deals of the Month! Every purchase comes with exclusive perks and offers, making this month a celebration of savvy choices and amazing deals. Don't miss out! 🎁🛒",
      days: "Days",
      hours: "Hours",
      minutes: "Minutes",
      seconds: "Seconds",
      loadingCountdown: "Loading Countdown...",
      dealHasEnded: "Deal Has Ended",
      dealHasEndedDescription:
        "This deal is no longer available. Check out our latest promotions!",
      viewProducts: "View Products",
      hidePromotion: "Hide promotion",
      showProductInfo: "Show product info",
    },
    COMPARISON: {
      title: "Product Comparison",
      empty: "No products to compare",
      addProducts: "Add products from the same category to compare",
      clearComparison: "Clear Comparison",
      comparisonCleared: "Comparison cleared",
      maxItems: "Maximum 4 products can be compared",
      differentCategory: "You can only compare products from the same category",
      alreadyAdded: "Product already in comparison",
      compareProducts: "Compare Products",
      feature: "Feature",
      cannotAddProduct: "Cannot add product to comparison",
    },
    WISHLIST: {
      title: "Wishlist",
      empty: "Your wishlist is empty",
      removedFromWishlist: "removed from wishlist",
    },
    CATEGORY_FORM: {
      categoryIdMissing: "Category ID is missing",
      slugRequired: "Slug is required and must be at least 3 characters",
      pleaseFixFormErrors: "Please fix the form errors before submitting",
      generateFromName: "Generate from name",
      categoryName: "Category Name",
      createCategory: "Create Category",
      updateCategory: "Update Category",
    },
    CHECKOUT_STEPS: {
      userLogin: "User Login",
      shippingAddress: "Shipping Address",
      paymentMethod: "Payment Method",
      placeOrder: "Place Order",
    },
    PROMOTION_FORM: {
      promotionEndDate: "Promotion End Date",
      enablePromotion: "Enable Promotion",
      disablePromotion: "Disable Promotion",
      setPromotion: "Set Promotion",
      clearPromotion: "Clear Promotion",
      uncheckToHidePromotion:
        "Uncheck to completely hide promotion from the site",
    },
    PURCHASE_RECEIPT: {
      orderConfirmation: "Order Confirmation",
      orderId: "Order ID",
      orderDate: "Order Date",
      orderTotal: "Order Total",
      orderStatus: "Order Status",
      orderItems: "Order Items",
      orderItem: "Order Item",
      pricePaid: "Price Paid",
      purchaseDate: "Purchase Date",
      items: "Items",
      tax: "Tax",
      shipping: "Shipping",
      total: "Total",
      viewOrderReceipt: "View Order Receipt",
      purchaseReceipt: "Purchase Receipt",
    },
  },
};

export default CONTENT_PAGE;
